title: My Personal Website
description: Personal website and blog
url: https://swoodipto.github.io
baseurl: "/sudip.to"
author: sudipto

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from being processed
exclude:
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# URL Settings
permalink: /:categories/:year/:month/:day/:title/ 