# Site Settings
title: My Personal Website
description: Personal website and blog
url: https://swoodipto.github.io
baseurl: "/sudip.to"
author: sudipto
lang: en
timezone: Asia/Kolkata

# SEO Settings
twitter:
  username: swoodipto
  card: summary
logo: /assets/images/logo.png
social:
  name: Sudipto
  links:
    - https://twitter.com/swoodipto
    - https://github.com/swoodipto

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      author: sudipto
      image: /assets/images/default-post.jpg
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

# Exclude from processing
exclude:
  - README.md
  - CHANGELOG.md
  - LICENSE
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  
# Include specific files/folders
include:
  - _pages
  - .htaccess

# URLs
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed
  sass_dir: _sass

# Feed settings
feed:
  path: feed.xml

# Additional settings
future: false
published: true
show_drafts: false
limit_posts: 0
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Environment settings
environment: production 